### ISSUE TITLE
 Practica03_Visual Studio Interfaz Grafica Menu_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipo-topicos-avanzados#1]
[Practica03_Visual Studio Interfaz Grafica Menu_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US.zip](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipo-topicos-avanzados/files/8121797/Practica03_Visual.Studio.Interfaz.Grafica.Menu_JudithReynaCruzSantiago_MariaJoseLopezLeyva_LitzyLopezLopez_4US.zip)

**Comment by SANDRAVELASCO** [comment]
Calificación: 20
